ES6 concept implemented to Awesome Book Project completely
Hidar37/Awesome-Book-Project-Using-ES6 pull request #1
Opened 2022-10-04 14:10 UTC by Hidar37

-` Arrow function` used in project.
- more `class `add to project.
- `import `and `export `concept implemented to project.
- `index.css` add.
-` index.html` add.
- all js files imported to `index.js`
- `luxon `package is used for `date and time`

2022-10-04 14:50 UTC, prolajumokeoni requested changes
Hi @Hidar37 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Git flow was correctly used
✔️  Good Readme



## Required Changes ♻️

- [x] Kindly make sure your app is working properly when I click on links on your navigation it does not take me to the right path, please fix this as it is important for your app to work 👍🏿 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


- [x] Kindly avoid overuse of disabling linters as it is not a good practice, it is better for your linters to pass the linter checks 👍🏿 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-04 14:50 UTC, prolajumokeoni commented on source/js/index.js
> +const now = DateTime.now();
- [ ] The current date should be  displayed below the navigation bar, part of the requirements is to  make sure your module import from luxon works, see video below ⬇️ 



https://user-images.githubusercontent.com/69638013/193848920-9ffb07c1-0eac-40af-abd9-8aacf237156c.mp4

2022-10-04 16:11 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @Hidar37 

Your project is complete! Great job for making the requested changes 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- navigation ok
- date from luxon library
- modules used
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-04 16:11 UTC, tufoinnkuo10 commented on source/js/index.js
> +  even.preventDefault();
- [optional] this is only optional because the previous reviewer said nothing about it. Please ensure that a book is being added and can as well be removed.

![demo3](https://user-images.githubusercontent.com/65298048/193870555-be6d6dba-3ffd-4c4b-8360-9b7202164f71.gif)

2022-10-04 16:13 UTC, merged

2022-10-05 11:49 UTC, prolajumokeoni commented on source/js/index.js
> +const now = DateTime.now();
- [ ] Glad you were able to get your project approved, I advise in future you add all instructions to run your application to your readme